### ISSUE TITLE
panic on Windows

### ISSUE THREAD

**Issue by mattn** [a-h/templ#29]
On Windows, templ stop working after starting. As far as I looked log file, it seems panic occurred.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x40 pc=0x96b52c]

goroutine 8 [running]:
github.com/sourcegraph/jsonrpc2.(*Conn).send(0x0, {0xc00009c040, 0xc0000718a0}, 0xc000086330, 0x1)
	C:/Users/mattn/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.1.0/jsonrpc2.go:352 +0x6c
github.com/sourcegraph/jsonrpc2.(*Conn).DispatchCall(0x0, {0xa2b078, 0xc000028440}, {0xc0000882d0, 0xa}, {0x98ff20, 0xc00009c040}, {0x0, 0x0, 0x0})
	C:/Users/mattn/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.1.0/jsonrpc2.go:449 +0x191
github.com/sourcegraph/jsonrpc2.(*Conn).Call(0x98ff20, {0xa2b078, 0xc000028440}, {0xc0000882d0, 0xc000094020}, {0x98ff20, 0xc00009c040}, {0x990260, 0xc0000b2000}, {0x0, ...})
	C:/Users/mattn/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.1.0/jsonrpc2.go:424 +0x72
github.com/a-h/templ/cmd/templ/lspcmd.(*Proxy).proxyInitialize(0xc000028480, {0xa2b078, 0xc000028440}, 0xc0000b0000, 0xc0000aa000)
	C:/Users/mattn/go/pkg/mod/github.com/a-h/templ@v0.0.148/cmd/templ/lspcmd/handler.go:230 +0x24b
github.com/a-h/templ/cmd/templ/lspcmd.(*Proxy).Handle(0xc000028480, {0xa2b078, 0xc000028440}, 0x0, 0xc0000aa000)
	C:/Users/mattn/go/pkg/mod/github.com/a-h/templ@v0.0.148/cmd/templ/lspcmd/handler.go:196 +0x75d
github.com/sourcegraph/jsonrpc2.(*Conn).readMessages(0xc00014a120, {0xa2b078, 0xc000028440})
	C:/Users/mattn/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.1.0/jsonrpc2.go:553 +0x2f8
created by github.com/sourcegraph/jsonrpc2.NewConn
	C:/Users/mattn/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.1.0/jsonrpc2.go:334 +0x28c

```

**Comment by a-h** [comment]
Having looked into this, it looks like the root cause is because you haven't got `gopls` on your path. templ uses the `gopls` server to provide autocomplete for the Go expressions, so if you haven't got it installed, it can't run it.

However, regardless of whether you've got the `gopls` executable installed, it shouldn't panic, so I've updated the code to check that `gopls` has been installed and to exit more gracefully.

I guess everyone that's installed templ so far already had it installed.

Thanks for letting me know about the problem, and do re-open the issue if this doesn't fix it.

For anyone that's interested, I was able to reproduce the issue on my Mac by changing the code to try and run `gopls2` instead of `gopls` (here's my LSP log from Neovim 5.x).

```sh
[ ERROR ] 2021-10-31T15:23:58+0000 ] ...m-unwrapped-0.5.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"templ"	"stderr"	"panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x11edb3e]\n\ngoroutine 20 [running]:\n"
[ ERROR ] 2021-10-31T15:23:58+0000 ] ...m-unwrapped-0.5.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"templ"	"stderr"	"github.com/sourcegraph/jsonrpc2.(*Conn).send(0x0, 0x12c4c78, 0xc000078400, 0xc000067370, 0x1, 0x0, 0x0, 0x0)\n\t/Users/adrian.hesketh/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.1.0/jsonrpc2.go:352 +0x7e\ngithub.com/sourcegraph/jsonrpc2.(*Conn).DispatchCall(0x0, 0x12c4c78, 0xc000078400, 0xc000018bc0, 0xa, 0x1218660, 0xc000078480, 0x0, 0x0, 0x0, ...)\n\t/Users/adrian.hesketh/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.1.0/jsonrpc2.go:449 +0x12b\ngithub.com/sourcegraph/jsonrpc2.(*Conn).Call(0x0, 0x12c4c78, 0xc000078400, 0xc000018bc0, 0xa, 0x1218660, 0xc000078480, 0x12189a0, 0xc000153110, 0x0, ...)\n\t/Users/adrian.hesketh/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.1.0/jsonrpc2.go:424 +0xa5\ngithub.com/a-h/templ/cmd/templ/lspcmd.(*Proxy).proxyInitialize(0xc0000a6000, 0x12c4c78, 0xc000078400, 0xc0000ac000, 0xc00007a370)\n\t/Users/adrian.hesketh/github.com/a-h/templ/cmd/templ/lspcmd/handler.go:230 +0x2d6\ngithub.com/a-h/templ/cmd/templ/lspcmd.(*Proxy).Handle(0xc0000a6000, 0x12c4c78, 0xc000078400, 0xc0000ac000, 0xc00007a370)\n\t/Users/adrian.hesketh/github.com/a-h/templ/cmd/templ/lspcmd/handler.go:196 +0xa4c\ngithub.com/sourcegraph/jsonrpc2.(*Conn).readMessages(0xc0000ac000, 0x12c4c78, 0xc000078400)\n\t/Users/adrian.hesketh/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.1.0/jsonrpc2.go:553 +0x57e\ncreated by github.com/sourcegraph/jsonrpc2.NewConn\n\t/Users/adrian.hesketh/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.1.0/jsonrpc2.go:334 +0x1d5\n"
```

**Comment by mattn** [comment]
Thanks for fixing this. But seems still having problem.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x4becd1]

goroutine 10 [running]:
github.com/a-h/templ/cmd/templ/lspcmd.(*Proxy).proxyInitialize(0xc000028440, {0x5746b8, 0xc000028400}, 0xc0000a0000?, 0xc000062050)
	C:/Users/mattn/go/src/github.com/a-h/templ/cmd/templ/lspcmd/handler.go:235 +0x391
github.com/a-h/templ/cmd/templ/lspcmd.(*Proxy).Handle(0xc000028440, {0x5746b8, 0xc000028400}, 0x0?, 0xc000062050)
	C:/Users/mattn/go/src/github.com/a-h/templ/cmd/templ/lspcmd/handler.go:196 +0x75d
github.com/sourcegraph/jsonrpc2.(*Conn).readMessages(0xc000152120, {0x5746b8, 0xc000028400})
	C:/Users/mattn/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.1.0/jsonrpc2.go:559 +0x2f8
created by github.com/sourcegraph/jsonrpc2.NewConn
	C:/Users/mattn/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.1.0/jsonrpc2.go:334 +0x28c
"]]

```
