### ISSUE TITLE
lsp: panic on autocomplete

### ISSUE THREAD

**Issue by pzeinlinger** [a-h/templ#490]
I'm experimenting with templ and found that the lsp consistently panics on the first auto-complete request (popover) in vscode. 

Initially, formatting works.

![Bildschirmaufzeichnung vom 2024-02-02, 21-25-55](https://github.com/a-h/templ/assets/26354635/40bed068-c058-4794-84c6-fd378972931b)

Version: v0.2.544-0.20240201214656-2b81fa260b1c

Stacktrace:
```
panic: runtime error: slice bounds out of range [39:38]

goroutine 1035 [running]:
github.com/a-h/templ/parser/v2/goexpression.SliceArgs.func1({0x9e9158?, 0xc000144ac0})
	/home/dev/go/pkg/mod/github.com/a-h/templ@v0.2.544-0.20240201214656-2b81fa260b1c/parser/v2/goexpression/parse.go:144 +0x17e
go/ast.inspector.Visit(0xc000608ab0, {0x9e9158?, 0xc000144ac0?})
	/nix/store/rccpgf2bnh58hhh4908p78i1rln9gzvp-go-1.21.5/share/go/src/go/ast/walk.go:386 +0x2b
go/ast.Walk({0x9e75e0?, 0xc000608ab0?}, {0x9e9158?, 0xc000144ac0?})
	/nix/store/rccpgf2bnh58hhh4908p78i1rln9gzvp-go-1.21.5/share/go/src/go/ast/walk.go:51 +0x5c
go/ast.walkExprList(...)
	/nix/store/rccpgf2bnh58hhh4908p78i1rln9gzvp-go-1.21.5/share/go/src/go/ast/walk.go:26
go/ast.Walk({0x9e75e0?, 0xc000608ab0?}, {0x9e9a40?, 0xc000130370?})
	/nix/store/rccpgf2bnh58hhh4908p78i1rln9gzvp-go-1.21.5/share/go/src/go/ast/walk.go:318 +0x1ccd
go/ast.Walk({0x9e75e0?, 0xc000608ab0?}, {0x9e9ab8?, 0xc000144b00?})
	/nix/store/rccpgf2bnh58hhh4908p78i1rln9gzvp-go-1.21.5/share/go/src/go/ast/walk.go:344 +0x1b85
go/ast.walkDeclList(...)
	/nix/store/rccpgf2bnh58hhh4908p78i1rln9gzvp-go-1.21.5/share/go/src/go/ast/walk.go:38
go/ast.Walk({0x9e75e0?, 0xc000608ab0?}, {0x9e9108?, 0xc000260140?})
	/nix/store/rccpgf2bnh58hhh4908p78i1rln9gzvp-go-1.21.5/share/go/src/go/ast/walk.go:366 +0x1b05
go/ast.Inspect(...)
	/nix/store/rccpgf2bnh58hhh4908p78i1rln9gzvp-go-1.21.5/share/go/src/go/ast/walk.go:397
github.com/a-h/templ/parser/v2/goexpression.SliceArgs({0xc0002260c0?, 0xc0?})
	/home/dev/go/pkg/mod/github.com/a-h/templ@v0.2.544-0.20240201214656-2b81fa260b1c/parser/v2/goexpression/parse.go:134 +0x14c
github.com/a-h/templ/parser/v2.parseGoSliceArgs(0xc0006083f0)
	/home/dev/go/pkg/mod/github.com/a-h/templ@v0.2.544-0.20240201214656-2b81fa260b1c/parser/v2/goparser.go:36 +0x9e
github.com/a-h/templ/parser/v2.glob..func22(0xc0006083f0)
	/home/dev/go/pkg/mod/github.com/a-h/templ@v0.2.544-0.20240201214656-2b81fa260b1c/parser/v2/stringexpressionparser.go:15 +0x125
github.com/a-h/parse.pf[...].Parse(...)
	/home/dev/go/pkg/mod/github.com/a-h/parse@v0.0.0-20240121214402-3caf7543159a/types.go:18
github.com/a-h/templ/parser/v2.templateNodeParser[...].Parse(0x0?, 0xc0006083f0?)
	/home/dev/go/pkg/mod/github.com/a-h/templ@v0.2.544-0.20240201214656-2b81fa260b1c/parser/v2/templateparser.go:101 +0x2f2
github.com/a-h/templ/parser/v2.elementOpenCloseParser.Parse({}, 0xc0006083f0)
	/home/dev/go/pkg/mod/github.com/a-h/templ@v0.2.544-0.20240201214656-2b81fa260b1c/parser/v2/elementparser.go:396 +0x1b1
github.com/a-h/parse.anyParser[...].Parse(...)
	/home/dev/go/pkg/mod/github.com/a-h/parse@v0.0.0-20240121214402-3caf7543159a/any.go:9
github.com/a-h/templ/parser/v2.elementParser.Parse({}, 0xc0006083f0)
	/home/dev/go/pkg/mod/github.com/a-h/templ@v0.2.544-0.20240201214656-2b81fa260b1c/parser/v2/elementparser.go:494 +0x125
github.com/a-h/templ/parser/v2.templateNodeParser[...].Parse(0xc000226054?, 0xc0006083f0?)
	/home/dev/go/pkg/mod/github.com/a-h/templ@v0.2.544-0.20240201214656-2b81fa260b1c/parser/v2/templateparser.go:101 +0x2f2
github.com/a-h/templ/parser/v2.glob..func19(0xc0006083f0)
	/home/dev/go/pkg/mod/github.com/a-h/templ@v0.2.544-0.20240201214656-2b81fa260b1c/parser/v2/parser.go:23 +0x196
github.com/a-h/parse.pf[...].Parse(...)
	/home/dev/go/pkg/mod/github.com/a-h/parse@v0.0.0-20240121214402-3caf7543159a/types.go:18
github.com/a-h/templ/parser/v2.TemplateFileParser.Parse({{0x0?, 0x0?}}, 0xc0006083f0)
	/home/dev/go/pkg/mod/github.com/a-h/templ@v0.2.544-0.20240201214656-2b81fa260b1c/parser/v2/templatefile.go:116 +0x48f
github.com/a-h/templ/parser/v2.ParseString({0xc000226000, 0xec})
	/home/dev/go/pkg/mod/github.com/a-h/templ@v0.2.544-0.20240201214656-2b81fa260b1c/parser/v2/templatefile.go:46 +0x1e7
github.com/a-h/templ/cmd/templ/lspcmd/proxy.(*Server).parseTemplate(0xc000130050, {0x9eb258, 0xc00010e720}, {0xc0002f4120, 0x2e}, {0xc000226000?, 0xc0001286c0?})
	/home/dev/go/pkg/mod/github.com/a-h/templ@v0.2.544-0.20240201214656-2b81fa260b1c/cmd/templ/lspcmd/proxy/server.go:123 +0xa8
github.com/a-h/templ/cmd/templ/lspcmd/proxy.(*Server).DidChange(0xc000130050, {0x9eb258, 0xc00010e720}, 0xc0006083c0)
	/home/dev/go/pkg/mod/github.com/a-h/templ@v0.2.544-0.20240201214656-2b81fa260b1c/cmd/templ/lspcmd/proxy/server.go:537 +0x449
github.com/a-h/protocol.serverDispatch({0x9eb258, 0xc00010e720}, {0x9efc20, 0xc000130050}, 0xc000608360, {0x7f98d0278198, 0xc00070b7a0})
	/home/dev/go/pkg/mod/github.com/a-h/protocol@v0.0.0-20230224160810-b4eec67c1c22/server.go:254 +0x3d13
github.com/a-h/protocol.NewServer.ServerHandler.func1({0x9eb258, 0xc00010e720}, 0xc000608360, {0x7f98d0278198, 0xc00070b7a0})
	/home/dev/go/pkg/mod/github.com/a-h/protocol@v0.0.0-20230224160810-b4eec67c1c22/server.go:36 +0x7e
github.com/a-h/protocol.Handlers.ReplyHandler.func1({0x9eb258, 0xc00010e720}, 0xc000202b40, {0x7f98d0278198?, 0xc00070b7a0?})
	/home/dev/go/pkg/mod/go.lsp.dev/jsonrpc2@v0.10.0/handler.go:35 +0xe5
github.com/a-h/protocol.Handlers.AsyncHandler.func2.2()
	/home/dev/go/pkg/mod/go.lsp.dev/jsonrpc2@v0.10.0/handler.go:114 +0x76
created by github.com/a-h/protocol.Handlers.AsyncHandler.func2 in goroutine 22
	/home/dev/go/pkg/mod/go.lsp.dev/jsonrpc2@v0.10.0/handler.go:112 +0x18f
[Error - 21:21:05] Server process exited with code 2.
[Error - 21:21:05] Connection to server got closed. Server will not be restarted.
[Error - 21:21:05] Delivering pending changes failed
TypeError: this.task is not a function
    at /home/dev/.vscode/extensions/a-h.templ-0.0.19/node_modules/vscode-languageclient/lib/common/utils/async.js:28:1
```

**Comment by a-h** [comment]
Thanks for the issue report. Very useful!

I can see you're running a pre release version, which I haven't tested the LSP side of very much yet.

If you didn't know that you were doing that, you might want to grab the latest tag instead by specify that in your flake reference, eg github:a-h/templ/v0.2.543

If you did know you were doing that, then thanks for trying out the main branch and finding issues, it's especially appreciated!

Was discussing today with Joe how to improve the testing in the LSP area. We don't have automated tests there at the moment.

**Comment by pzeinlinger** [comment]
I was very excited to try out the new txt based hot reloading mode! Thanks for the great work!
Is there any way I can help out?

**Comment by a-h** [comment]
After I figure out what I'm doing wrong with the new Go expression parser to make the LSP crash (presumably, I need to handle the parser failure cases where Go expressions are in variously invalid states in a better way), then the next task is to build out some LSP tests so that we don't have regressions in this area again.

@joerdav and I are thinking to do something along these lines: https://github.com/golang/tools/blob/master/gopls/internal/test/integration/completion/completion_test.go#L47

So, depending on how much time/inclination you have, either writing the framework to manage the LSP tests for templ, or, when @joerdav and/or I get to it, adding a good suite of tests would be useful.

If you're up for general templ stuff, then another priority is support for media queries in the CSS handling. @joerdav is thinking along these lines:

```templ
css c() {
    @mediaquerya {
        width: 1;
    }
    @mediaqueryb {
        width: 2;
    }
    width: 3;
}
```

Would produce the following CSS output:

```css
.c {
    width: 3;
}
@mediaquerya {
    .c {
        width: 1;
    }
}
@mediaqueryb {
    .c {
        width: 2;
    }
}
```
