### ISSUE TITLE
Concurrent map read and write error

### ISSUE THREAD

**Issue by soyangel** [a-h/templ#547]
Hi,

Using version 0.2.543 got the following error when running  **template generate -watch** 

```
fatal error: concurrent map read and map write

goroutine 10 [running]:
github.com/a-h/templ/cmd/templ/generatecmd.generate({0x9d4fb0, 0xc0000244b0}, {0xc000028510, 0x29}, {0xc000034880, 0x36}, 0xc0001a4d50, 0x0, {0xc000060ce0, 0x2, ...})
	github.com/a-h/templ/cmd/templ/generatecmd/main.go:421 +0x7a9
github.com/a-h/templ/cmd/templ/generatecmd.processSingleFile({0x9d4fb0, 0xc0000244b0}, {0x9cf2c0?, 0xc000088030}, {0xc000028510, 0x29}, {0xc000034880, 0x36}, 0x0?, 0x0, ...)
	github.com/a-h/templ/cmd/templ/generatecmd/main.go:349 +0x10b
github.com/a-h/templ/cmd/templ/generatecmd.processChanges.func1.1()
	github.com/a-h/templ/cmd/templ/generatecmd/main.go:311 +0xf7
created by github.com/a-h/templ/cmd/templ/generatecmd.processChanges.func1 in goroutine 1
	github.com/a-h/templ/cmd/templ/generatecmd/main.go:309 +0x77e

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc0000c3380?)
	runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0xc000028510?)
	sync/waitgroup.go:116 +0x48
github.com/a-h/templ/cmd/templ/generatecmd.processChanges({0x9d4fb0?, 0xc0000244b0}, {0x9cf2c0?, 0xc000088030}, 0xc0001ad918, 0xc0001a4d50, {0xc000028510, 0x29}, 0x0, {0xc0000880c0, ...}, ...)
	github.com/a-h/templ/cmd/templ/generatecmd/main.go:324 +0x3e5
github.com/a-h/templ/cmd/templ/generatecmd.generateWatched({0x9d4fb0, 0xc0000244b0}, {0x9cf2c0?, 0xc000088030}, {{0x0, 0x0}, {0xc000028510, 0x29}, 0x1, 0x1, ...}, ...)
	github.com/a-h/templ/cmd/templ/generatecmd/main.go:142 +0x2f9
github.com/a-h/templ/cmd/templ/generatecmd.runCmd({0x9d4fb0, 0xc0000244b0}, {0x9cf2c0, 0xc000088030}, {{0x0, 0x0}, {0xc000028510, 0x29}, 0x1, 0x1, ...})
	github.com/a-h/templ/cmd/templ/generatecmd/main.go:119 +0x618
github.com/a-h/templ/cmd/templ/generatecmd.Run({0x9d4fb0?, 0xc0000244b0?}, {0x9cf2c0?, 0xc000088030?}, {{0x0, 0x0}, {0x7fffdc647b98, 0x9}, 0x1, 0x1, ...})
	github.com/a-h/templ/cmd/templ/generatecmd/main.go:63 +0x13b
main.generateCmd({0x9cf2c0?, 0xc000088030}, {0xc0000240c0, 0x3, 0x3})
	github.com/a-h/templ/cmd/templ/main.go:144 +0x698
main.run({0x9cf2c0, 0xc000088030}, {0xc0000240a0?, 0xc50038?, 0xc0000061a0?})
	github.com/a-h/templ/cmd/templ/main.go:48 +0x1c8
main.main()
	github.com/a-h/templ/cmd/templ/main.go:21 +0x36

goroutine 7 [syscall]:
os/signal.signal_recv()
	runtime/sigqueue.go:152 +0x29
os/signal.loop()
	os/signal/signal_unix.go:23 +0x13
created by os/signal.Notify.func1.1 in goroutine 1
	os/signal/signal.go:151 +0x1f

goroutine 8 [chan receive]:
main.generateCmd.func1()
	github.com/a-h/templ/cmd/templ/main.go:140 +0x34
created by main.generateCmd in goroutine 1
	github.com/a-h/templ/cmd/templ/main.go:139 +0x509

goroutine 12 [runnable]:
fmt.(*buffer).writeString(...)
	fmt/print.go:108
fmt.(*pp).doPrintf(0xc0002244e0, {0x92060d, 0x1c}, {0xc0002bbe98?, 0x2, 0x2})
	fmt/print.go:1034 +0x12e
fmt.Fprintf({0x9cf500, 0xc000524a20}, {0x92060d, 0x1c}, {0xc0002bbe98, 0x2, 0x2})
	fmt/print.go:224 +0x71
github.com/a-h/templ/cmd/templ/generatecmd.logWithDecoration({0x9cf500, 0xc000524a20}, {0x90f4cc, 0x3}, 0xc000034b40?, {0x92060d, 0x1c}, {0xc0002bbe98, 0x2, 0x2})
	github.com/a-h/templ/cmd/templ/generatecmd/main.go:485 +0x105
github.com/a-h/templ/cmd/templ/generatecmd.logSuccess(...)
	github.com/a-h/templ/cmd/templ/generatecmd/main.go:480
github.com/a-h/templ/cmd/templ/generatecmd.processSingleFile({0x9d4fb0, 0xc0000244b0}, {0x9cf2c0?, 0xc000088030}, {0xc000028510, 0x29}, {0xc000034b40, 0x38}, 0x0?, 0x0, ...)
	github.com/a-h/templ/cmd/templ/generatecmd/main.go:362 +0x3cd
github.com/a-h/templ/cmd/templ/generatecmd.processChanges.func1.1()
	github.com/a-h/templ/cmd/templ/generatecmd/main.go:311 +0xf7
created by github.com/a-h/templ/cmd/templ/generatecmd.processChanges.func1 in goroutine 1
	github.com/a-h/templ/cmd/templ/generatecmd/main.go:309 +0x77e

```

**Comment by a-h** [comment]
Yes, sorry about that. There's a new release coming once https://github.com/a-h/templ/pull/546 is merged which contains a fix for that.

I've basically rewritten the watch mode from scratch in https://github.com/a-h/templ/pull/470

**Comment by soyangel** [comment]
That new watch mode looks awesome... Good job! 👏👏👏

**Comment by joerdav** [comment]
Closing since resolved in upcoming release. Please feel free to open again if it pops up again.
